### ISSUE TITLE
如何实现一日三检（即单账号每天有三次不同时间的签到）

### ISSUE THREAD

**Issue by LiarOnce** [IceTiki/ruoli-sign-optimization#112]
这么配置不能顺利签到，如果按照多账号配置的话会不会出问题?
```yaml
users: 
  -
    type: 1 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: [马赛克] # 学校全称
    username: "[马赛克]" # 学号或者工号
    password: "[马赛克]" # 密码
    # 一般需填项-------
    abnormalReason: "" # 范围外签到原因
    photo: "" # 签到照片(不需要可不填)
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    checkTitle: 1 # 是否检查表单各项的标题[1:检查|0:不检查]
    forms: 
      # 一检
      - form:
          title: 早晨的身体健康情况
          value: 健康
      - form:
          title: 早晨的体温是多少
          value: 正常（36.0℃-37.2℃）
      # 二检
      - form:
          title: 中午的身体健康情况
          value: 健康
      - form:
          title: 中午的体温是多少
          value: 正常（36.0℃-37.2℃）
      # 三检
      - form:
          title: 晚上的身体健康情况
          value: 健康
      - form:
          title: 晚上的体温是多少
          value: 正常（36.0℃-37.2℃）
    lon: [马赛克]
    lat: [马赛克]
    address: "[马赛克]"
```
