### ISSUE TITLE
请教配置多用户

### ISSUE THREAD

**Issue by bug1615** [IceTiki/ruoli-sign-optimization#32]
大佬，请问配置多个用户的代码格式要怎么写？可以发一下参考的示例吗？谢谢

**Comment by IceTiki** [comment]
```yaml
author: 若离|IceTiki|https://github.com/IceTiki/ruoli-sign-optimization
# YAML有引用和锚点，可以节省配置长度(备注:锚点要放在引用的前面)(可以参考https://www.runoob.com/w3cnote/yaml-intro.html)
# ======================================================================
# 全局设置
# ======================================================================
locationOffsetRange: 50 # 坐标偏移范围(单位：米)(可以为0)
maxTry: 1 # 最大尝试次数
logDir: "log/" # 日志保存地址
delay: [5, 10] # 多用户时，各用户之间任务执行延迟(时间范围可以使用浮点数)
sendMessage: # 推送函数的整体运行情况(不需要的项目不用填，可以删掉或者放着不管)
  rl_emailApiUrl: http://api.ruoli.cc/mail/sendMail # 邮箱API的地址
  rl_email: "" # email 接受通知消息的邮箱
  qmsg_key: "" # qmsg推送的key
  qmsg_qq: "" # qmsg推送的qq号
  qmsg_isGroup: 0 # 此qq号是否为群(是的话填1，反之为0)
  pushplus_parameters: "" # pushplus参数，填入令牌(token)即可推送。也可以填入"token=xxx&topic=xxx"形式自定义更多参数
  pushplus_isNew: False # False使用旧版pushplus(https://pushplus.hxtrip.com)，True使用新版pushplus(http://www.pushplus.plus/)
  smtp_host: "smtp.qq.com" # SMTP服务器域名
  smtp_user: "*****@qq.com" # SMTP服务器用户名
  smtp_key: "" # SMTP服务器密钥
  smtp_sender: "*****@qq.com" # 发送邮箱
  smtp_receivers:
    - "*****@qq.com" # 接收邮箱(可填多个)
# ======================================================================
# 用户组配置(填写自己所需的类型，并删掉不需要的。可以多用户签到。)
# ======================================================================
users: # ------别误删了这一行------
  - # 签到模板=======我是用户1
    # 通用必填项-------
    type: 1 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 五道口职业技术学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: sign.jpg # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    signLevel: 1 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # 签到任务的标题(使用正则表达式进行匹配(注: yaml中单引号包裹字符串不进行转义，适合写正则表达式))[0:自动取最后一个未签到的任务]
    getHistorySign: True

  - # 签到模板=======我是用户2
    # 通用必填项-------
    type: 1 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 五道口职业技术学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: sign.jpg # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    signLevel: 1 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # 签到任务的标题(使用正则表达式进行匹配(注: yaml中单引号包裹字符串不进行转义，适合写正则表达式))[0:自动取最后一个未签到的任务]
    getHistorySign: True

  - # 签到模板=======我是用户3
    # 通用必填项-------
    type: 1 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 五道口职业技术学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: sign.jpg # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    signLevel: 1 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # 签到任务的标题(使用正则表达式进行匹配(注: yaml中单引号包裹字符串不进行转义，适合写正则表达式))[0:自动取最后一个未签到的任务]
    getHistorySign: True

```
