### ISSUE TITLE
推送提示语

### ISSUE THREAD

**Issue by bug1615** [IceTiki/ruoli-sign-optimization#35]
==签到成功==
[默认备注名]
--202030306|1
--该收集已填写无需再次填写

==签到成功==
[默认备注名]
--202030306|1
--SUCCESS

请问能否自定义提示语？就是后面那句“--该收集已填写无需再次填写”、“--SUCCESS”。

**Comment by IceTiki** [comment]
目前没有这个功能。
我觉得增加这个功能会使代码更加臃肿，一般信息推送只要能看得懂就可以，没有自定义语句的强烈需求。

**Comment by bug1615** [comment]
> 目前没有这个功能。 我觉得增加这个功能会使代码更加臃肿，一般信息推送只要能看得懂就可以，没有自定义语句的强烈需求。

好的，谢谢

**Comment by bug1615** [comment]
> 目前没有这个功能。 我觉得增加这个功能会使代码更加臃肿，一般信息推送只要能看得懂就可以，没有自定义语句的强烈需求。

大佬，依旧是获取历史表单问题，在日志中看到能获取历史表单，但是没有正常填写信息收集。(看到获取了最初始的信息收集)
<br>
<br>
```

获取到第1页历史信息收集数据

code: '0'

datas:

  pageNumber: 1

  pageSize: 20

  rows:

  - content: https://wecres.cpdaily.com/counselor/1020369334696620/html/9fea874f2ab143afaa6543595f90705f.html

    createTime: 2022-03-08 18:36

    currentTime: '2022-03-09 21:34:19'

    endTime: 2022-03-09 20:35

    formWid: '1135'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 老师(城市轨道交通与信息工程系)

    startTime: 2022-03-08 20:35

    subject: 根据省教育厅要求进行疫情信息上报的信息收集。

    wid: '106039'

  - content: https://wecres.cpdaily.com/counselor/1020369334696620/html/13c6260a11f0479cbfb2cbc4b3fc975a.html

    createTime: 2022-03-07 20:03

    currentTime: '2022-03-09 21:34:19'

    endTime: 2022-03-08 20:47

    formWid: '1133'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 老师(城市轨道交通与信息工程系)

    startTime: 2022-03-07 20:47

    subject: 根据省教育厅要求进行疫情信息上报的信息收集。

  - content: https://wecres.cpdaily.com/counselor/1020369334696620/html/7d0cbf6e0e8f4af6a0f8113097ab37af.html

    createTime: 2022-03-06 17:09

    currentTime: '2022-03-09 21:34:19'

    endTime: 2022-03-07 20:04

    formWid: '1131'

    wid: '105928'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 老师(城市轨道交通与信息工程系)

    startTime: 2022-03-06 20:04

    subject: 根据省教育厅要求进行疫情信息上报的信息收集。

    wid: '105772'

  - content: https://wecres.cpdaily.com/counselor/1020369334696620/html/f5926b4abaf9458fafceb9bb9cbde65b.html

    createTime: 2022-03-05 21:24

    currentTime: '2022-03-09 21:34:19'

    endTime: 2022-03-06 21:22

    formWid: '1129'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 老师(城市轨道交通与信息工程系)

    startTime: 2022-03-05 21:30

    subject: 根据省教育厅要求进行疫情信息上报的信息收集。

    wid: '105627'

  - content: ''

    createTime: 2022-03-04 19:14

    currentTime: '2022-03-09 21:34:19'

    endTime: 2022-03-05 21:12

    formWid: '1127'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 老师(城市轨道交通与信息工程系)

    startTime: 2022-03-04 20:12

    subject: 根据省教育厅要求进行疫情信息上报的信息收集。

    wid: '105479'


.......


 - content: https://wecres.cpdaily.com/counselor/1020369334696620/content/75d98655212f499b908a733c81735fd9.html

    createTime: 2020-10-31 22:42

    currentTime: '2022-03-09 21:34:21'

    endTime: 2020-11-01 14:00

    formWid: '412'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 城市轨道交通与信息工程系(老师)

    startTime: 2020-11-01 00:00

    subject: 【教育厅】根据省教育厅要求进行疫情信息上报的信息收集

    wid: '35318'

  - content: https://wecres.cpdaily.com/counselor/1020369334696620/content/5709050a89964285b2ef2610eb2555ba.html

    createTime: 2020-10-30 20:32

    currentTime: '2022-03-09 21:34:21'

    endTime: 2020-10-31 14:00

    formWid: '411'

    instanceWid: null

    isHandled: 1

    isRead: 1

    priority: '5'

    senderUserName: 城市轨道交通与信息工程系(老师)

Response RequestId:7e6c4b5d-628a-4ce6-a52c-8d15676f9970 RetMsg:"ok"

END RequestId:7e6c4b5d-628a-4ce6-a52c-8d15676f9970

Report RequestId:7e6c4b5d-628a-4ce6-a52c-8d15676f9970 Duration:13080ms Memory:128MB MemUsage:31.329475MB

```
<br>
<br>
<br>

**Comment by IceTiki** [comment]
你试试用最新版本。
在config.yml中填好信息收集任务标题(在title里面填，可以参考示例的config.yml)

**Comment by IceTiki** [comment]
搞定了说一声(

**Comment by bug1615** [comment]
> 你试试用最新版本。 在config.yml中填好信息收集任务标题(在title里面填，可以参考示例的config.yml)

”在title里面填“是什么意思？

**Comment by bug1615** [comment]
> 搞定了说一声(

```
author: 若离|IceTiki|https://github.com/IceTiki/ruoli-sign-optimization
# YAML有引用和锚点，可以节省配置长度(备注:锚点要放在引用的前面)(可以参考https://www.runoob.com/w3cnote/yaml-intro.html)
# ======================================================================
# 全局设置
# ======================================================================
locationOffsetRange: 50 # 坐标偏移范围(单位：米)(可以为0)
maxTry: 1 # 最大尝试次数
logDir: "log/" # 日志保存地址
delay: [5, 10] # 多用户时，各用户之间任务执行延迟(时间范围可以使用浮点数)
sendMessage: # 推送函数的整体运行情况(不需要的项目不用填，可以删掉或者放着不管)
  rl_emailApiUrl: http://api.ruoli.cc/mail/sendMail # 邮箱API的地址
  rl_email: "" # email 接受通知消息的邮箱
  qmsg_key: "" # qmsg推送的key
  qmsg_qq: "" # qmsg推送的qq号
  qmsg_isGroup: 0 # 此qq号是否为群(是的话填1，反之为0)
  pushplus_parameters: "" # pushplus参数，填入令牌(token)即可推送。也可以填入"token=xxx&topic=xxx"形式自定义更多参数
  pushplus_isNew: False # False使用旧版pushplus(https://pushplus.hxtrip.com)，True使用新版pushplus(http://www.pushplus.plus/)
  smtp_host: "smtp.qq.com" # SMTP服务器域名
  smtp_user: "@qq.com" # SMTP服务器用户名
  smtp_key: "" # SMTP服务器密钥
  smtp_sender: "@qq.com" # 发送邮箱
  smtp_receivers:
    - "@qq.com" # 接收邮箱(可填多个)
# ======================================================================
# 用户组配置(填写自己所需的类型，并删掉不需要的。可以多用户签到。)
# ======================================================================
users: # ------别误删了这一行------
  - # 信息收集模板=======
    # 通用必填项-------
    type: 0 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 某校 # 学校全称
    username: "4654645" # 学号或者工号
    password: "55646" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    signLevel: 1 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # 签到任务的标题(使用正则表达式进行匹配(注: yaml中单引号包裹字符串不进行转义，适合写正则表达式))[0:自动取最后一个未签到的任务]
    getHistorySign: true
    checkTitle: 1 # 是否检查表单的标题（1:检查|0:不检查）
    lon: 1..... # 经度
    lat: 3....... # 纬度
    address: "某地" # 地址信息
```
<br>
<br>
部署了最新的版本，config.yml配置如上，报错如下
<br>
<br>

```
|||V-T3.5.1|||warn|||16.727s|||

没有找到匹配的历史任务


|||V-T3.5.1|||info|||16.729s|||

--46564545|1

--没有找到匹配的历史任务


|||V-T3.5.1|||info|||16.729s|||

推送情况


Qmsg配置错误，信息取消发送

邮件配置出错

邮箱或邮件api填写无效，已取消发送邮件！

pushplus的令牌填写错误，已取消发送！


|||V-T3.5.1|||info|||16.729s|||

==签到情况==

[默认备注名]

--456464556|1

--没有找到匹配的历史任务



|||V-T3.5.1|||info|||18.155s|||

推送情况


Qmsg配置错误，信息取消发送

邮件发送成功

邮箱或邮件api填写无效，已取消发送邮件！

pushplus的令牌填写错误，已取消发送！


Response RequestId:1a9a9b5e-7143-4dda-8d57-8b5d13b5a75b RetMsg:"ok"

END RequestId:1a9a9b5e-7143-4dda-8d57-8b5d13b5a75b

Report RequestId:1a9a9b5e-7143-4dda-8d57-8b5d13b5a75b Duration:17685ms Memory:128MB MemUsage:31.303680MB
```
