### ISSUE TITLE
出现未知表单类型（健康码: 24）

### ISSUE THREAD

**Issue by MeetinaXD** [IceTiki/ruoli-sign-optimization#86]
出现未知表单类型，请反馈『{'wid': '120703', 'formWid': '4811', 'fieldType': '24', 'title': '请上传您今天的健康码', 'description': '', 'warningDescription': '请上传当日真实的健康码截图。瞒报信息可能会给您造成不便，甚至承担相关法律责任。', 'isRequired': True, 'hasOtherItems': False, 'sort': 7, 'colName': 'field007', 'fieldItems': [], 'scoringRule': '-1', 'score': None, 'answerContent': None, 'basicConfig': {'minValue': None, 'maxValue': None, 'decimals': None, 'dateFormatType': None, 'dateType': None, 'pointTime': None, 'minTime': None, 'maxTime': None, 'extremeLabel': None, 'level': None, 'isReversal': None, 'leftValue': None, 'rightValue': None, 'voteType': None, 'voteMinValue': None, 'voteMaxValue': None, 'addressIsRequired': None, 'abnormalRemind': None}, 'logicWid': 9, 'value': '', 'show': True, 'answerIsCorrect': None, 'answerScore': None, 'imageAnalysisVo': None, 'formType': '0', 'sortNum': '7'}』

**Comment by MeetinaXD** [comment]
新的今日校园增加了“健康码识别”和“行程码识别”功能，提交时会识别，但不需要等待识别完毕就能提交。

**Comment by IceTiki** [comment]
你健康码和行程码是同一题吗

**Comment by IceTiki** [comment]
有可能行程码的type不是24，给一下完整日志看一下(要获取表单返回的结果)

**Comment by MeetinaXD** [comment]
不是同一题，以下为日志
```
|||V-T3.9.1c|||info|||0.059s|||
正在进行第1轮尝试

|||V-T3.9.1c|||info|||0.059s|||
即将在第1轮尝试中为[**********]签到

|||V-T3.9.1c|||debug|||0.059s|||
程序正在暂停5.630秒

|||V-T3.9.1c|||info|||5.693s|||
准备登录

|||V-T3.9.1c|||info|||8.734s|||
登录完成

|||V-T3.9.1c|||info|||8.734s|||
即将开始信息收集填报

|||V-T3.9.1c|||info|||9.413s|||
获取到的第1页任务列表
code: '0'
datas:
  pageNumber: 1
  pageSize: 20
  rows:
  - content: https://wecres.cpdaily.com/counselor/1020383251920324/html/cc9e869782aa41e4874d9ce827b3a429.html
    createTime: 2022-08-29 10:23
    currentTime: '2022-08-29 11:40:51'
    endTime: 2022-08-29 16:30
    formWid: '4811'
    instanceWid: null
    isHandled: 0
    isRead: 1
    priority: '4'
    senderUserName: ***
    startTime: 2022-08-29 06:36
    subject: ****学生健康
    wid: '70600'
  totalSize: 1
message: SUCCESS


|||V-T3.9.1c|||info|||9.524s|||
查询任务详情返回结果
collector:
  address: null
  attachmentNames: null
  attachmentSizes: null
  attachmentUrls: null
  createTime: '2022-08-29 10:23:08'
  currentTime: '2022-08-29 11:40:51'
  endTime: '2022-08-29 16:30:00'
  fetchStuLocation: true
  formWid: '4811'
  instanceWid: null
  isConfirmed: 0
  isLocationFailedSub: false
  isShowAnswer: false
  isUserSubmit: 0
  priority: '4'
  schoolTaskWid: '227055'
  senderUserName: ***
  subject: ***学生健康
  wid: '70600'
form:
  attachments: []
  backReason: null
  confirmDesc: 确认已认真查看，且填写信息无误
  examTime: null
  formContent: https://wecres.cpdaily.com/counselor/1020383251920324/html/cc9e869782aa41e4874d9ce827b3a429.html
  formTitle: ***学生健康
  formType: '0'
  isAnonymous: 0
  isBack: 0
  isallowUpdated: 1
  isshowOrdernum: 1
  isshowResult: 0
  isshowScore: 0
  score: 0
  stuScore: null
  wid: '4811'


|||V-T3.9.1c|||info|||9.628s|||
查询任务表单返回结果
existData: 0
isShowAnswer: null
isShowScore: null
rows:
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: null
    minTime: null
    minValue: null
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field001
  description: ''
  fieldItems:
  - basicConfig: null
    content: 是
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253611'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 否
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253612'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  fieldType: '2'
  formWid: '4811'
  hasOtherItems: false
  imageAnalysisVo: null
  isRequired: true
  logicWid: 1
  score: null
  scoringRule: '-1'
  show: false
  sort: 1
  title: 本日您是否有发烧症状（体温37.3℃以上）
  value: ''
  warningDescription: null
  wid: '120697'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: '4'
    minTime: null
    minValue: '1'
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field002
  description: （可多选）
  fieldItems:
  - basicConfig: null
    content: 未离开居住地
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253613'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 国内中高风险地区
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253614'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 国境外
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253615'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig:
      abnormalRemind: null
      addressIsRequired: null
      dateFormatType: null
      dateType: null
      decimals: 0
      extremeLabel: null
      isReversal: null
      leftValue: null
      level: null
      maxTime: null
      maxValue: '1000'
      minTime: null
      minValue: '1'
      pointTime: null
      rightValue: null
      voteMaxValue: null
      voteMinValue: null
      voteType: null
    content: 其他
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: true
    isSelected: null
    itemWid: '253616'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  fieldType: '3'
  formWid: '4811'
  hasOtherItems: true
  imageAnalysisVo: null
  isRequired: true
  logicWid: 2
  score: null
  scoringRule: '-1'
  show: false
  sort: 2
  title: 前14天至今，您本人到过的地点（含途经）
  value: ''
  warningDescription: null
  wid: '120698'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: '4'
    minTime: null
    minValue: '1'
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field003
  description: （可多选）
  fieldItems:
  - basicConfig: null
    content: 无相关接触史
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253617'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 从中高风险地区回来的人员
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253618'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 近14天从国（境）外回来人员
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253619'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 确诊或者疑似的病患人员
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253620'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  fieldType: '3'
  formWid: '4811'
  hasOtherItems: false
  imageAnalysisVo: null
  isRequired: true
  logicWid: 3
  score: null
  scoringRule: '-1'
  show: false
  sort: 3
  title: 前14天至今，您本人是否接触过以下人员
  value: ''
  warningDescription: null
  wid: '120699'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: '7'
    minTime: null
    minValue: '1'
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field004
  description: （可多选）
  fieldItems:
  - basicConfig: null
    content: 健康，没有出现相关疾病症状
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253621'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 咳嗽
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253622'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 乏力，肌肉疼痛
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253623'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 呼吸困难
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253624'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 心慌、胸闷
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253625'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 恶心、呕吐、腹泻
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253626'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig:
      abnormalRemind: null
      addressIsRequired: null
      dateFormatType: null
      dateType: null
      decimals: 0
      extremeLabel: null
      isReversal: null
      leftValue: null
      level: null
      maxTime: null
      maxValue: '1000'
      minTime: null
      minValue: '1'
      pointTime: null
      rightValue: null
      voteMaxValue: null
      voteMinValue: null
      voteType: null
    content: 其他
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: true
    isSelected: null
    itemWid: '253627'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  fieldType: '3'
  formWid: '4811'
  hasOtherItems: true
  imageAnalysisVo: null
  isRequired: true
  logicWid: 4
  score: null
  scoringRule: '-1'
  show: false
  sort: 4
  title: 今天您本人的健康情况
  value: ''
  warningDescription: null
  wid: '120700'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: '4'
    minTime: null
    minValue: '1'
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field005
  description: （可多选）（仅填现在与您共同生活的家人情况）
  fieldItems:
  - basicConfig: null
    content: 所有家人身体均健康，正常
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253628'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 有家人有发热、咳嗽、乏力、呼吸急促等不适症状其中的一项或者多项
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253629'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 有家人被列为确诊或者疑似新型冠状病毒感染对象
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253630'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig:
      abnormalRemind: null
      addressIsRequired: null
      dateFormatType: null
      dateType: null
      decimals: 0
      extremeLabel: null
      isReversal: null
      leftValue: null
      level: null
      maxTime: null
      maxValue: '1000'
      minTime: null
      minValue: '1'
      pointTime: null
      rightValue: null
      voteMaxValue: null
      voteMinValue: null
      voteType: null
    content: 其他
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: true
    isSelected: null
    itemWid: '253631'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  fieldType: '3'
  formWid: '4811'
  hasOtherItems: true
  imageAnalysisVo: null
  isRequired: true
  logicWid: 5
  score: null
  scoringRule: '-1'
  show: false
  sort: 5
  title: 今天您的家人身体健康情况
  value: ''
  warningDescription: null
  wid: '120701'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: null
    minTime: null
    minValue: null
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field006
  description: 如您的健康码发生变化，请第一时间告知辅导员老师
  fieldItems:
  - basicConfig: null
    content: 绿码
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253632'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 黄码
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253633'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  - basicConfig: null
    content: 红码
    contentExtend: ''
    imageUrl: null
    isAnswer: false
    isOtherItems: false
    isSelected: null
    itemWid: '253634'
    otherItemType: '1'
    score: null
    selectCount: null
    showLogic: ''
    showLogicArray: null
    totalCount: 0
  fieldType: '2'
  formWid: '4811'
  hasOtherItems: false
  imageAnalysisVo: null
  isRequired: true
  logicWid: 6
  score: null
  scoringRule: '-1'
  show: false
  sort: 6
  title: 您今天的粤康码和户籍所在地健康码是
  value: ''
  warningDescription: null
  wid: '120702'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: null
    minTime: null
    minValue: null
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field007
  description: ''
  fieldItems: []
  fieldType: '24'
  formWid: '4811'
  hasOtherItems: false
  imageAnalysisVo: null
  isRequired: true
  logicWid: 9
  score: null
  scoringRule: '-1'
  show: false
  sort: 7
  title: 请上传您今天的健康码
  value: ''
  warningDescription: 请上传当日真实的健康码截图。瞒报信息可能会给您造成不便，甚至承担相关法律责任。
  wid: '120703'
- answerContent: null
  answerIsCorrect: null
  answerScore: null
  basicConfig:
    abnormalRemind: null
    addressIsRequired: null
    dateFormatType: null
    dateType: null
    decimals: null
    extremeLabel: null
    isReversal: null
    leftValue: null
    level: null
    maxTime: null
    maxValue: null
    minTime: null
    minValue: null
    pointTime: null
    rightValue: null
    voteMaxValue: null
    voteMinValue: null
    voteType: null
  colName: field008
  description: ''
  fieldItems: []
  fieldType: '25'
  formWid: '4811'
  hasOtherItems: false
  imageAnalysisVo: null
  isRequired: true
  logicWid: 10
  score: null
  scoringRule: '-1'
  show: false
  sort: 8
  title: 请上次您今天的行程卡
  value: ''
  warningDescription: 请上传当日真实的行程码截图。瞒报信息可能会给您造成不便，甚至承担相关法律责任。
  wid: '120704'
totalSize: 8


|||V-T3.9.1c|||info|||9.630s|||
填充表单

|||V-T3.9.1c|||info|||9.631s|||
--***|1
--『***学生健康』
出现未知表单类型，请反馈『{'wid': '120703', 'formWid': '4811', 'fieldType': '24', 'title': '请上传您今天的健康码', 'description': '', 'warningDescription': '请上传当日真实的健康码截图。瞒报信息可能会给您造成不便，甚至承担相关法律责任。', 'isRequired': True, 'hasOtherItems': False, 'sort': 7, 'colName': 'field007', 'fieldItems': [], 'scoringRule': '-1', 'score': None, 'answerContent': None, 'basicConfig': {'minValue': None, 'maxValue': None, 'decimals': None, 'dateFormatType': None, 'dateType': None, 'pointTime': None, 'minTime': None, 'maxTime': None, 'extremeLabel': None, 'level': None, 'isReversal': None, 'leftValue': None, 'rightValue': None, 'voteType': None, 'voteMinValue': None, 'voteMaxValue': None, 'addressIsRequired': None, 'abnormalRemind': None}, 'logicWid': 9, 'value': '', 'show': True, 'answerIsCorrect': None, 'answerScore': None, 'imageAnalysisVo': None, 'formType': '0', 'sortNum': '7'}』

|||V-T3.9.1c|||info|||9.631s|||
『***』用户推送情况
推送情况

QMSG酱|无效配置
SMTP|无效配置
若离邮箱API|无效配置
IceCream|无效配置
Pushplus|无效配置

|||V-T3.9.1c|||info|||9.631s|||
『全局签到情况(0/1)[V-T3.9.1c]』
[默认备注名]
--***|1
--『***学生健康』
出现未知表单类型，请反馈『{'wid': '120703', 'formWid': '4811', 'fieldType': '24', 'title': '请上传您今天的健康码', 'description': '', 'warningDescription': '请上传当日真实的健康码截图。瞒报信息可能会给您造成不便，甚至承担相关法律责任。', 'isRequired': True, 'hasOtherItems': False, 'sort': 7, 'colName': 'field007', 'fieldItems': [], 'scoringRule': '-1', 'score': None, 'answerContent': None, 'basicConfig': {'minValue': None, 'maxValue': None, 'decimals': None, 'dateFormatType': None, 'dateType': None, 'pointTime': None, 'minTime': None, 'maxTime': None, 'extremeLabel': None, 'level': None, 'isReversal': None, 'leftValue': None, 'rightValue': None, 'voteType': None, 'voteMinValue': None, 'voteMaxValue': None, 'addressIsRequired': None, 'abnormalRemind': None}, 'logicWid': 9, 'value': '', 'show': True, 'answerIsCorrect': None, 'answerScore': None, 'imageAnalysisVo': None, 'formType': '0', 'sortNum': '7'}』
Running at 2022-08-29 11:40:41, using 9.63s
1: 0todo, 0done, 0skip, 1error, 0notFound

|||V-T3.9.1c|||info|||11.101s|||
全局推送情况
推送情况

QMSG酱|无效配置
SMTP|邮件发送成功
若离邮箱API|无效配置
IceCream|无效配置
Pushplus|无效配置
```
